# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 23:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('piece_of_music', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BandEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.Event')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Band')),
            ],
            options={
                'abstract': False,
            },
            bases=('quickstart.event',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.Person')),
            ],
            bases=('quickstart.person',),
        ),
        migrations.CreateModel(
            name='EnsembleEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.Event')),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Ensemble')),
            ],
            options={
                'abstract': False,
            },
            bases=('quickstart.event',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.Person')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Band')),
            ],
            bases=('quickstart.person',),
        ),
        migrations.CreateModel(
            name='Pianist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.Person')),
            ],
            bases=('quickstart.person',),
        ),
        migrations.CreateModel(
            name='SoloEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.Event')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Instrument')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Participant')),
            ],
            options={
                'abstract': False,
            },
            bases=('quickstart.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='competition_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Class'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_quickstart.event_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='event',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Director'),
        ),
        migrations.AddField(
            model_name='event',
            name='pianist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Pianist'),
        ),
    ]
